[package]
name = "rust_raylib"
version = "0.1.0"
edition = "2024"

[dependencies]
raylib ={ version = "5.5" }
winapi = { version = "0.3", features = ["winuser"] }
mki = "0.2.3"
rand = "0.9.1"
yaml-rust2 = "0.10.2"